import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const spaceGrotesk = localFont({
	src: './fonts/SpaceGrotesk.woff',
	variable: '--font-space-grotesk',
	weight: '100, 200, 300, 400, 500, 600, 700, 800, 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${spaceGrotesk.className} antialiased`}>
				{children}
			</body>
		</html>
	);
}
