import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ReactQueryProvider from '@/common/providers/ReactQueryProvider';
import { draftMode } from 'next/headers';
import { DisableDraftMode } from '@/common/components/sanity/DisableDraftMode';
import { VisualEditing } from 'next-sanity';
import { SanityLive } from '@/sanity/lib/live';
import Navigation from '@/common/components/global/Navigation';
import { getGlobalData } from '@/common/lib/getGlobalData';
import GlobalDataProvider from '@/common/providers/global-data-provider';

const spaceGrotesk = localFont({
	src: './fonts/SpaceGrotesk.woff',
	variable: '--font-space-grotesk',
	weight: '100, 200, 300, 400, 500, 600, 700, 800, 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const data = await getGlobalData();

	return (
		<ReactQueryProvider>
			<html lang="en">
				<body className={`${spaceGrotesk.className} antialiased`}>
					<GlobalDataProvider globalData={data}>
						<>
							<Navigation />
							{children}
							<SanityLive />
							{(await draftMode()).isEnabled && (
								<>
									<DisableDraftMode />
									<VisualEditing />
								</>
							)}
						</>
					</GlobalDataProvider>
				</body>
			</html>
		</ReactQueryProvider>
	);
}
